{{- if .Values.vpa.enabled -}}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "bentopdf.fullname" . }}
  labels:
    {{- include "bentopdf.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       {{ include "bentopdf.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.vpa.updatePolicy.updateMode | quote }}
  {{- if not (empty .Values.vpa.resourcePolicy) }}
  resourcePolicy:
    {{- toYaml .Values.vpa.resourcePolicy | nindent 4 }}
  {{- end }}
{{- end }}
