{{- if .Values.httproute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "technitium.fullname" . }}
  {{- with .Values.httproute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "technitium.labels" . | nindent 4 }}
spec:
  parentRefs:
    {{- toYaml .Values.httproute.parentRefs | nindent 4 }}
  hostnames:
    {{- toYaml .Values.httproute.hostnames | nindent 4 }}
  rules:
    {{- toYaml .Values.httproute.rules | nindent 4 }}
{{- end }}
