{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "technitium.fullname" . }}-secret
  labels:
    {{- include "technitium.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secret.adminPassword }}
  DNS_SERVER_ADMIN_PASSWORD: {{ .Values.secret.adminPassword | b64enc | quote }}
  {{- end }}
{{- end }}
