{{- if .Values.autoscaling.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "technitium.fullname" . }}
  labels:
    {{- include "technitium.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: {{ .Values.controller.kind }}
    name: {{ include "technitium.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.autoscaling.vpa.updateMode | quote }}
  {{- if .Values.autoscaling.vpa.resourcePolicy }}
  resourcePolicy:
    {{- toYaml .Values.autoscaling.vpa.resourcePolicy | nindent 4 }}
  {{- end }}
{{- end }}
