apiVersion: v2
name: mealie
description: A Helm chart for Kubernetes
type: application
version: 1.0.1
appVersion: "v3.9.2"
home: https://mealie.io/
icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/mealie.png
sources:
  - https://github.com/mealie-recipes/mealie
  - https://github.com/deimosfr/deimosfr-charts
maintainers:
  - name: deimosfr
    email: deimosfr@gmail.com
keywords:
  - mealie
  - recipe
  - manager
  - self-hosted
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial chart release
  artifacthub.io/images: |
    - name: mealie
      image: ghcr.io/mealie-recipes/mealie:v3.9.2
  artifacthub.io/category: "integration-delivery"
