apiVersion: v1
kind: Service
metadata:
  name: {{ include "stepifi.fullname" . }}
  labels:
    {{- include "stepifi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.bullBoardPort }}
      targetPort: bull-board
      protocol: TCP
      name: bull-board
  selector:
    {{- include "stepifi.selectorLabels" . | nindent 4 }}
