apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mealie.fullname" . }}
  labels:
    {{- include "mealie.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.mealie.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := .Values.mealie.email }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
