{{- if .Values.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "mealie.fullname" . }}
  labels:
    {{- include "mealie.labels" . | nindent 4 }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefs | nindent 4 }}
  hostnames:
    {{- toYaml .Values.httpRoute.hostnames | nindent 4 }}
  rules:
    {{- if .Values.httpRoute.rules }}
    {{- toYaml .Values.httpRoute.rules | nindent 4 }}
    {{- else }}
    {{- if .Values.httpRoute.cors.enabled }}
    - matches:
        - path:
            type: PathPrefix
            value: /
          method: OPTIONS
      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              - name: Access-Control-Allow-Origin
                value: {{ .Values.httpRoute.cors.allowOrigin | quote }}
              - name: Access-Control-Allow-Methods
                value: {{ .Values.httpRoute.cors.allowMethods | quote }}
              - name: Access-Control-Allow-Headers
                value: {{ .Values.httpRoute.cors.allowHeaders | quote }}
              - name: Access-Control-Max-Age
                value: {{ .Values.httpRoute.cors.maxAge | quote }}
              - name: Content-Length
                value: "0"
      backendRefs:
        - name: {{ include "mealie.fullname" . }}
          port: {{ .Values.service.port }}
    {{- end }}
    - matches:
        - path:
            type: PathPrefix
            value: /
      {{- if .Values.httpRoute.cors.enabled }}
      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              - name: Access-Control-Allow-Origin
                value: {{ .Values.httpRoute.cors.allowOrigin | quote }}
              - name: Access-Control-Allow-Methods
                value: {{ .Values.httpRoute.cors.allowMethods | quote }}
              - name: Access-Control-Allow-Headers
                value: {{ .Values.httpRoute.cors.allowHeaders | quote }}
              - name: Access-Control-Expose-Headers
                value: {{ .Values.httpRoute.cors.exposeHeaders | quote }}
      {{- end }}
      backendRefs:
        - name: {{ include "mealie.fullname" . }}
          port: {{ .Values.service.port }}
    {{- end }}
{{- end }}
