apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mealie.fullname" . }}
  labels:
    {{- include "mealie.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.mealie.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
