{{- if .Values.vpa.enabled -}}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "mealie.fullname" . }}
  labels:
    {{- include "mealie.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "mealie.fullname" . }}
  {{- if .Values.vpa.updateMode }}
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode | quote }}
  {{- end }}
  {{- if .Values.vpa.containerPolicies }}
  resourcePolicy:
    containerPolicies:
      {{- toYaml .Values.vpa.containerPolicies | nindent 6 }}
  {{- end }}
{{- end }}
