apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ddns-updater.fullname" . }}
  labels:
    {{- include "ddns-updater.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.json: |
    {{- toPrettyJson .Values.config | nindent 4 }}
